import type { Metadata } from 'next';

export const siteConfig: Metadata = {
  title: 'Codestam Jira',
  description: 'Full-stack Codestam Jira using Next.js 14 and Appwrite.',
  keywords: [
    'reactjs',
    'nextjs',
    'appwrite',
    'appwrite-io',
    'next-auth',
    'react-big-calendar',
    'lucide-icons',
    'react-icons',
    'react-day-picker',
    'shadcn-ui',
    'radix-ui',
    'tailwindcss',
    'lodash',
    'react-query',
    'nuqs',
    'sonner',

    'typescript',
    'javascript',
    'vercel',
    'postcss',
    'prettier',
    'eslint',
    'react-dom',
    'html',
    'css',

    'nuqs-state-management',
    'infinite-query',
    'real-time-features',
    'organized-table',
    'filter-table',
    'paginate-table',
    'tasks-management',
    'projects-management',
    'workspaces-management',
    'ui/ux',
    'appwrite-db',
    'jira-clone',

    'date-fns',
    'cn',
    'clsx',
    'lucide-react',
  ] as Array<string>,
  authors: {
    name: 'Codestam Technologies',
    url: 'https://github.com/CodestamTechnologies/jira.git',
  },
} as const;
