import React from 'react'
import {
  Document,
  Page,
  Text,
  View,
} from '@react-pdf/renderer'

import { registerPDFFonts } from '@/lib/pdf/fonts'
import { pdfStyles } from '@/lib/pdf/styles'
import {
  Letterhead,
  Section,
  SubSection,
  Separator,
  BulletList,
  SignatureBox,
  DocumentTitle,
} from '@/lib/pdf/components'
import { COMPANY_INFO as SHARED_COMPANY_INFO } from '@/lib/pdf/constants'

// Register fonts once
registerPDFFonts()

export interface NDAData {
  companyName?: string
  companyAddress?: string
  companyCIN?: string
  employeeName: string
  employeeAddress: string
  employeeAadhar: string
  effectiveDate: string
  logoUrl?: string
}

const NDAPDF: React.FC<NDAData> = ({
  companyName = SHARED_COMPANY_INFO.legalName,
  companyAddress = SHARED_COMPANY_INFO.address,
  companyCIN = SHARED_COMPANY_INFO.cin,
  employeeName,
  employeeAddress,
  employeeAadhar,
  effectiveDate,
  logoUrl = SHARED_COMPANY_INFO.logoUrl,
}) => {
  return (
    <Document>
      <Page size="A4" style={pdfStyles.page}>
        {/* Letterhead */}
        <Letterhead
          logoUrl={logoUrl}
          companyName={SHARED_COMPANY_INFO.name}
          legalName={companyName}
          cin={companyCIN}
          address={companyAddress}
        />

        <Separator type="double" />

        {/* Document Title */}
        <DocumentTitle
          title="EMPLOYEE NON-DISCLOSURE, NON-COMPETE, AND INTELLECTUAL PROPERTY ASSIGNMENT AGREEMENT"
        />

        <Separator type="double" />

        {/* Agreement Introduction */}
        <Text style={pdfStyles.bodyText}>
          This Agreement ("Agreement") is made and entered into as of the{' '}
          <Text style={pdfStyles.bold}>{effectiveDate}</Text>{' '}
          ("Effective Date"),
        </Text>

        {/* Parties Section */}
        <Text style={pdfStyles.partyLabel}>BETWEEN:</Text>
        <Text style={pdfStyles.partyText}>
          {companyName}, a company incorporated under the Companies Act, 2013, having its registered office at {companyAddress}, (hereinafter referred to as the "Company", which expression shall, unless repugnant to the context or meaning thereof, include its successors, affiliates, and permitted assigns),
        </Text>

        <Text style={pdfStyles.partyLabel}>AND:</Text>
        <Text style={pdfStyles.partyText}>
          {employeeName}, residing at {employeeAddress},
        </Text>
        <Text style={pdfStyles.partyText}>
          ID Proof – Aadhar No.- {employeeAadhar},
        </Text>
        <Text style={pdfStyles.partyText}>
          (hereinafter referred to as the "Employee", which expression shall, unless repugnant to the context, include his/her heirs, legal representatives, and assigns).
        </Text>

        <Separator />

        {/* Section 1: PURPOSE */}
        <Section number="1" title="PURPOSE">
          <Text style={pdfStyles.bodyText}>
            The Employee acknowledges that, in the course of employment with the Company, he/she will have access to and may contribute to the creation of Confidential Information (as defined below) concerning the Company's business, products, clients, and proprietary technology. The purpose of this Agreement is to define and protect the Company's legitimate business interests, proprietary rights, and trade secrets, and to impose on the Employee a strict obligation of confidentiality, non-solicitation, and non-competition.
          </Text>
        </Section>

        {/* Section 2: DEFINITION OF CONFIDENTIAL INFORMATION */}
        <Section number="2" title="DEFINITION OF CONFIDENTIAL INFORMATION">
          <Text style={pdfStyles.bodyText}>
            "Confidential Information" includes but is not limited to:
          </Text>
          <BulletList
            items={[
              "Technical information, software, algorithms, source code, documentation, system architecture, APIs, databases, models, frameworks, and scripts.",
              "Business information such as client lists, pricing models, quotations, proposals, contracts, vendor data, marketing strategies, and sales records.",
              "Financial data, forecasts, budgets, and company performance information.",
              "Operational processes, project workflows, internal tools, and policies.",
              "Information received from clients, partners, or affiliates under confidentiality obligations.",
              "All work product, code, inventions, designs, ideas, and intellectual property developed by the Employee during employment.",
              "Any data, reports, or analytics created, accessed, or handled by the Employee, including those generated by automated systems or AI tools within the Company's infrastructure.",
            ]}
          />
          <Text style={pdfStyles.bodyText}>
            Confidential Information shall remain the sole property of the Company, whether created or acquired during employment or after its termination, and regardless of whether such information is designated as "confidential."
          </Text>
        </Section>

        {/* Section 3: OBLIGATIONS OF CONFIDENTIALITY */}
        <Section number="3" title="OBLIGATIONS OF CONFIDENTIALITY">
          <Text style={pdfStyles.bodyText}>
            The Employee agrees:
          </Text>
          <BulletList
            items={[
              "To maintain absolute secrecy over all Confidential Information, whether or not marked as confidential.",
              "Not to disclose, reproduce, transmit, or communicate any Confidential Information to any unauthorized person or entity.",
              "To use Confidential Information solely for the purposes of performing duties for the Company.",
              "Not to remove, copy, or store any Confidential Information outside authorized Company systems or devices without written consent.",
              "To immediately report to the Company any unauthorized use, loss, or disclosure of Confidential Information.",
              "That obligations of confidentiality shall continue in perpetuity, including after the termination of employment, for any reason.",
              "These obligations shall apply regardless of whether the Employee uses Company-issued or personal devices, including laptops, phones, drives, or cloud accounts, to access or handle Company data.",
            ]}
          />
        </Section>

        {/* Section 4: OWNERSHIP AND ASSIGNMENT OF INTELLECTUAL PROPERTY */}
        <Section number="4" title="OWNERSHIP AND ASSIGNMENT OF INTELLECTUAL PROPERTY">
          <BulletList
            items={[
              "The Employee agrees that all inventions, software, designs, concepts, documentation, trade secrets, and any other work product (\"Inventions\") created, developed, or conceived during the term of employment, whether alone or jointly with others, and which relate to the Company's business or make use of its resources, shall be the exclusive property of the Company.",
              "The Employee hereby irrevocably assigns to the Company all rights, title, and interest in and to such Inventions, including all intellectual property rights worldwide.",
              "The Employee shall execute any documents or take actions necessary to perfect or enforce the Company's ownership of such rights.",
              "The Employee waives any moral rights, future claims, or royalties arising from such work product.",
              "The Employee agrees that all code, technical documentation, and materials created during employment are \"works made for hire\" to the fullest extent permitted by law.",
            ]}
          />
        </Section>

        {/* Section 5: NON-COMPETE */}
        <Section number="5" title="NON-COMPETE">
          <Text style={pdfStyles.bodyText}>
            The Employee agrees that during the term of employment and for a period of twenty-four (24) months following termination (for any reason), the Employee shall not, directly or indirectly, engage in or be employed by, consult for, or have any financial interest in any business that competes with the Company's operations, including but not limited to:
          </Text>
          <BulletList
            items={[
              "Software development agencies",
              "Automation or AI solution providers",
              "Digital transformation consultancies",
              "Any business that solicits or serves the Company's clients.",
            ]}
          />
          <Text style={pdfStyles.bodyText}>
            This restriction applies globally to the extent the Company or its clients operate or intend to operate.
          </Text>
          <Text style={pdfStyles.bodyText}>
            The Employee acknowledges that the non-compete restriction is reasonable and necessary to protect the Company's legitimate business interests and proprietary data.
          </Text>
        </Section>

        {/* Section 6: NON-SOLICITATION */}
        <Section number="6" title="NON-SOLICITATION">
          <Text style={pdfStyles.bodyText}>
            During employment and for a period of twenty-four (24) months following termination, the Employee shall not directly or indirectly solicit, induce, or attempt to solicit:
          </Text>
          <BulletList
            items={[
              "Any client, vendor, or business partner of the Company.",
              "Any employee, consultant, or contractor of the Company to terminate or alter their relationship with the Company.",
            ]}
          />
          <Text style={pdfStyles.bodyText}>
            The Employee shall not participate in or assist any competitor, directly or indirectly, in soliciting or engaging clients previously or currently associated with the Company.
          </Text>
        </Section>

        {/* Section 7: COMPANY PROPERTY AND DATA SECURITY */}
        <Section number="7" title="COMPANY PROPERTY AND DATA SECURITY">
          <BulletList
            items={[
              "All devices, access credentials, source code, files, hardware, or software provided by the Company remain the Company's property and must be returned immediately upon termination or upon request.",
              "The Employee shall not use personal storage devices, email accounts, or external cloud systems to store or transfer Company data.",
              "The Employee shall not install, modify, or replicate Company software or repositories without authorization.",
              "The Employee shall comply with the Company's cybersecurity, password management, and data protection policies at all times, regardless of device ownership.",
              "Any intentional data breach, code theft, or unauthorized access to production environments constitutes criminal misconduct and may be pursued under the Information Technology Act, 2000, and the Indian Penal Code.",
              "These obligations extend equally to all personally owned devices used for official work or connected to Company systems in any capacity.",
            ]}
          />
        </Section>

        {/* Section 8: PROBATION PERIOD POLICY */}
        <Section number="8" title="PROBATION PERIOD POLICY">
          <BulletList
            items={[
              "Every new employee will undergo a probation period of three (3) months.",
              "During this period, employees cannot resign or leave the organization without official approval.",
              "The payment for the probation period will be released after successful completion of the probation, based on performance and project completion.",
              "The official offer letter will be issued only after the successful completion of the probation period and confirmation of employment.",
            ]}
          />
        </Section>

        {/* Section 9: RESIGNATION & EXIT POLICY */}
        <Section number="9" title="RESIGNATION & EXIT POLICY">
          <BulletList
            items={[
              "Employees are not permitted to leave the organization without written approval from management.",
              "A notice period (as defined in your offer letter after probation) must be served before resignation.",
              "Unauthorized absences or sudden exits will be reported to your college placement department, and you may be opted out of the placement program.",
            ]}
          />
        </Section>

        {/* Section 10: LOCKING PERIOD POLICY */}
        <Section number="10" title="LOCKING PERIOD POLICY">
          <Text style={pdfStyles.bodyText}>
            A mandatory locking period of one (1) year will start from the date of issuance of the official offer letter.
          </Text>
          <Text style={pdfStyles.bodyText}>
            During this period, the employee is expected to remain with the company and work on assigned projects.
          </Text>
          <Text style={pdfStyles.bodyText}>
            If an employee:
          </Text>
          <BulletList
            items={[
              "Leaves the company before completing the locking period,",
              "Joins another company without written approval, or",
              "Fails to follow the terms of this agreement,",
            ]}
          />
          <Text style={pdfStyles.bodyText}>
            Then the company has the right to:
          </Text>
          <BulletList
            items={[
              "Recover any expenses or investments made for the employee (training, placement assistance, etc.),",
              "Impose a monetary penalty if needed, and",
              "Report the violation to the college placement department, and",
              "Remove the employee from any ongoing or future placement opportunities.",
            ]}
          />
        </Section>

        {/* Section 11: DISCLOSURE OF CONFLICTS OF INTEREST */}
        <Section number="11" title="DISCLOSURE OF CONFLICTS OF INTEREST">
          <Text style={pdfStyles.bodyText}>
            The Employee shall promptly disclose any actual or potential conflict of interest, including outside employment, personal projects, or investments that overlap with the Company's business interests. Failure to disclose such conflicts shall be deemed a material breach of this Agreement.
          </Text>
        </Section>

        {/* Section 12: REMEDIES */}
        <Section number="12" title="REMEDIES">
          <BulletList
            items={[
              "The Employee acknowledges that any violation of this Agreement will cause irreparable harm to the Company that cannot be remedied by monetary damages alone.",
              "The Company shall be entitled to seek injunctive relief, restraining orders, and all other equitable remedies without the need to post bond or prove actual damages.",
              "The Company also retains the right to claim damages, legal costs, and any profits gained by the Employee from the breach.",
              "The Company may pursue criminal prosecution under applicable Indian cyber and trade secret laws for theft, data misuse, or unauthorized disclosure.",
            ]}
          />
        </Section>

        {/* Section 13: TERMINATION */}
        <Section number="13" title="TERMINATION">
          <Text style={pdfStyles.bodyText}>
            Upon termination of employment, the Employee shall:
          </Text>
          <BulletList
            items={[
              "Immediately return all Company property, devices, passwords, and materials.",
              "Permanently delete or destroy any copies (digital or physical) of Confidential Information retained.",
              "Provide a written declaration of compliance confirming return and destruction of all such material.",
              "Ensure any personal devices used for official work are inspected or cleared by the Company's IT team before reuse or disposal.",
            ]}
          />
        </Section>

        {/* Section 14: GOVERNING LAW AND JURISDICTION */}
        <Section number="14" title="GOVERNING LAW AND JURISDICTION">
          <BulletList
            items={[
              "This Agreement shall be governed by and construed in accordance with the laws of India.",
              "The courts of Ranchi, Jharkhand shall have exclusive jurisdiction over any dispute arising under or in connection with this Agreement.",
              "No arbitration or mediation clause shall limit the Company's right to seek direct judicial remedy.",
            ]}
          />
        </Section>

        {/* Section 15: SEVERABILITY */}
        <Section number="15" title="SEVERABILITY">
          <Text style={pdfStyles.bodyText}>
            If any clause or provision of this Agreement is deemed invalid or unenforceable, the remainder shall continue in full force and effect.
          </Text>
        </Section>

        {/* Section 16: NO WAIVER */}
        <Section number="16" title="NO WAIVER">
          <Text style={pdfStyles.bodyText}>
            Failure by the Company to enforce any provision of this Agreement shall not constitute a waiver of its rights. All rights and remedies remain cumulative and enforceable.
          </Text>
        </Section>

        {/* Section 17: ENTIRE AGREEMENT */}
        <Section number="17" title="ENTIRE AGREEMENT">
          <Text style={pdfStyles.bodyText}>
            This Agreement supersedes all prior understandings, representations, and agreements, whether oral or written, relating to confidentiality, IP, or employment restrictions between the Employee and the Company.
          </Text>
        </Section>

        {/* Section 18: SURVIVAL */}
        <Section number="18" title="SURVIVAL">
          <Text style={pdfStyles.bodyText}>
            All provisions relating to confidentiality, intellectual property, non-compete, non-solicitation, and remedies shall survive termination of employment indefinitely.
          </Text>
        </Section>

        {/* Section 19: ANNEXURE: RELEVANT INDIAN LEGAL PROVISIONS */}
        <Section number="19" title="ANNEXURE: RELEVANT INDIAN LEGAL PROVISIONS">
          <Text style={pdfStyles.bodyText}>
            The Employee acknowledges and agrees that any act of data theft, code exfiltration, digital intrusion, or intentional harm to the Company's systems may constitute criminal offences under the following provisions, among others:
          </Text>

          <SubSection title="Information Technology Act, 2000 (as amended):">
            <BulletList
              items={[
                "Section 43: Penalty for unauthorized access, data theft, or damage to computer systems or networks.",
                "Section 65: Tampering with computer source documents.",
                "Section 66: Hacking and dishonest use of computer resources.",
                "Section 66B: Dishonestly receiving stolen computer resources or communication devices.",
                "Section 66C: Identity theft and misuse of credentials.",
                "Section 66D: Cheating by personation using computer resources.",
                "Section 66E: Violation of privacy through image or data capture.",
                "Section 72 & 72A: Breach of confidentiality and privacy by a person having lawful access to data.",
                "Section 85: Offences by companies, where both the company and responsible individuals can be prosecuted.",
              ]}
            />
          </SubSection>

          <SubSection title="Indian Penal Code, 1860:">
            <BulletList
              items={[
                "Section 405 & 408: Criminal breach of trust by an employee or servant.",
                "Section 415 & 420: Cheating and dishonestly inducing delivery of property or valuable information.",
                "Section 425 & 426: Mischief causing wrongful loss or damage to the Company.",
                "Sections 463–477A: Forgery, falsification of accounts, and tampering with electronic records.",
                "Section 379: Theft of data or property.",
                "Section 409: Criminal breach of trust by public servant or agent.",
              ]}
            />
          </SubSection>

          <Text style={pdfStyles.bodyText}>
            Any breach under these provisions may lead to criminal prosecution, fines, imprisonment, and recovery of damages by the Company in both civil and criminal forums.
          </Text>
        </Section>

        {/* Section 20: ENFORCEMENT AND CONTINUING OBLIGATION */}
        <Section number="20" title="ENFORCEMENT AND CONTINUING OBLIGATION">
          <Text style={pdfStyles.bodyText}>
            The Employee agrees that:
          </Text>
          <BulletList
            items={[
              "These obligations are continuing and enforceable even if the Employee's role, compensation, or position changes.",
              "The Company may pursue parallel civil and criminal remedies without limitation.",
              "All obligations under this Agreement are binding upon the Employee's estate, heirs, and legal representatives.",
              "All clauses herein apply fully and equally irrespective of whether the Employee uses Company-issued or personally owned hardware or software for official purposes.",
            ]}
          />
        </Section>

        {/* Section 21: ACKNOWLEDGMENT */}
        <Section number="21" title="ACKNOWLEDGMENT">
          <Text style={pdfStyles.bodyText}>
            The Employee acknowledges:
          </Text>
          <BulletList
            items={[
              "They have read, understood, and voluntarily accepted this Agreement.",
              "They had the opportunity to seek independent legal advice prior to signing.",
              "They understand that breach of this Agreement may lead to immediate termination, legal proceedings, and civil or criminal liability.",
              "They understand that this Agreement and all its provisions apply equally when performing official work on personal devices, including laptops, phones, storage, or external drives.",
            ]}
          />
        </Section>

        <Separator type="double" />

        {/* Signature Section */}
        <Text style={pdfStyles.sectionHeading}>IN WITNESS WHEREOF</Text>
        <Text style={pdfStyles.bodyText}>
          The parties have executed this Agreement on the date first written above.
        </Text>

        <View style={pdfStyles.signatureSection}>
          <SignatureBox
            label={`For ${companyName}`}
            fields={[
              { label: 'Name' },
              { label: 'Designation' },
              { label: 'Signature' },
              { label: 'Date' },
            ]}
          />

          <SignatureBox
            label="For Employee"
            fields={[
              { label: 'Name', value: employeeName },
              { label: 'Signature' },
              { label: 'Date' },
            ]}
          />
        </View>
      </Page>
    </Document>
  )
}

export default NDAPDF
